# This is a basic workflow to help you get started with Actions

name: release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:
  
  push:
    tags:
    - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lemur:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      image: paulmedwards/lfsazsync-lemur-almalinux87:latest
      options: --user 0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: get version tag
        run: echo "version_tag=$(git describe --tags --always --dirty | tr '-' '_')" >> $GITHUB_ENV

      - name: print release name
        run: echo "version tag = ${{ env.version_tag }}"

      # Runs a single command using the runners shell
      - name: build lemur tarball
        run: build/lemur/build_lemur.sh
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.version_tag }}
          files: |
            /github/home/lfsazsync/build/lemur/lemur.tgz
  robinhood:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      image: paulmedwards/lfsazsync-robinhood-almalinux87:latest
      options: --user 0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: get version tag
        run: echo "version_tag=$(git describe --tags --always --dirty | tr '-' '_')" >> $GITHUB_ENV

      - name: print release name
        run: echo "version tag = ${{ env.version_tag }}"

      # Runs robinhood tarball
      - name: Build RPMs
        run: build/robinhood/build_robinhood.sh
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.version_tag }}
          files: |
            /github/home/lfsazsync/build/robinhood/robinhood.tgz