# This is a basic workflow to help you get started with Actions

name: release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:
  
  push:
    tags:
    - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu2004-lemur:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      image: paulmedwards/lfsazsync-lemur-ubuntu2004:latest
      options: --user 0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: get repo dir
        run: echo "repo_dir=$(pwd)" >> $GITHUB_ENV

      - name: fix git detected dubious ownership in repository
        run: git config --global --add safe.directory ${{ env.repo_dir }}

      - name: get version tag
        run: echo "version_tag=$(git describe --tags --always --dirty | tr '-' '_')" >> $GITHUB_ENV

      - name: print release name
        run: echo "version tag = ${{ env.version_tag }}"

      - name: build lemur tarball
        run: build/lemur/build_lemur.sh
      
      - name: rename lemur tarball to include os name
        run: mv ${{ env.repo_dir }}/build/lemur/lemur.tgz ${{ env.repo_dir }}/build/lemur/ubuntu2004-lemur.tgz

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.version_tag }}
          files: |
            ${{ env.repo_dir }}/build/lemur/ubuntu2004-lemur.tgz

  almalinux87-lemur:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      image: paulmedwards/lfsazsync-lemur-almalinux87:latest
      options: --user 0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: get repo dir
        run: echo "repo_dir=$(pwd)" >> $GITHUB_ENV

      - name: fix git detected dubious ownership in repository
        run: git config --global --add safe.directory ${{ env.repo_dir }}

      - name: get version tag
        run: echo "version_tag=$(git describe --tags --always --dirty | tr '-' '_')" >> $GITHUB_ENV

      - name: print release name
        run: echo "version tag = ${{ env.version_tag }}"

      - name: build lemur tarball
        run: build/lemur/build_lemur.sh
      
      - name: rename lemur tarball to include os name
        run: mv ${{ env.repo_dir }}/build/lemur/lemur.tgz ${{ env.repo_dir }}/build/lemur/almalinux87-lemur.tgz

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.version_tag }}
          files: |
            ${{ env.repo_dir }}/build/lemur/almalinux87-lemur.tgz

  ubuntu2004-robinhood:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      image: paulmedwards/lfsazsync-robinhood-ubuntu2004:latest
      options: --user 0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: get repo directory
        run: echo "repo_dir=$(pwd)" >> $GITHUB_ENV

      - name: fix git detected dubious ownership in repository
        run: git config --global --add safe.directory ${{ env.repo_dir }}

      - name: get version tag
        run: echo "version_tag=$(git describe --tags --always --dirty | tr '-' '_')" >> $GITHUB_ENV

      - name: print release name
        run: echo "version tag = ${{ env.version_tag }}"

      - name: build robinhood tarball
        run: build/robinhood/build_robinhood.sh
      
      - name: rename robinhood tarball to include os name
        run: mv ${{ env.repo_dir }}/build/robinhood/robinhood.tgz ${{ env.repo_dir }}/build/robinhood/ubuntu2004-robinhood.tgz

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.version_tag }}
          files: |
            ${{ env.repo_dir }}/build/robinhood/ubuntu2004-robinhood.tgz
  
  almalinux87-robinhood:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      image: paulmedwards/lfsazsync-robinhood-almalinux87:latest
      options: --user 0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: get repo directory
        run: echo "repo_dir=$(pwd)" >> $GITHUB_ENV

      - name: fix git detected dubious ownership in repository
        run: git config --global --add safe.directory ${{ env.repo_dir }}

      - name: get version tag
        run: echo "version_tag=$(git describe --tags --always --dirty | tr '-' '_')" >> $GITHUB_ENV

      - name: print release name
        run: echo "version tag = ${{ env.version_tag }}"

      - name: build robinhood tarball
        run: build/robinhood/build_robinhood.sh
      
      - name: rename robinhood tarball to include os name
        run: mv ${{ env.repo_dir }}/build/robinhood/robinhood.tgz ${{ env.repo_dir }}/build/robinhood/almalinux87-robinhood.tgz

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.version_tag }}
          files: |
            ${{ env.repo_dir }}/build/robinhood/almalinux87-robinhood.tgz
